name: Github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm install --legacy-peer-deps
      - run: npm run docs:build:sub

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_dir: ./docs-dist
          publish_branch: pages
